/** Phase 8 Wave D projection and safe rich-content tools. */
import type { Drawing, DrawingTool } from "@/types";
import type { HitResult, HitTestProjector } from "../../hittest/HitTestEngine";
import { TOL, defaultMovePoints, distToSegment, registerTool, type DrawingToolPlugin } from "../ToolRegistry";
import { canvasFont, handle } from "./shared";
import type { Anchor } from "../ToolRegistry";

type XY={x:number;y:number};
function projected(d:Drawing,toX:HitTestProjector,toY:HitTestProjector){return d.points.flatMap(p=>{const x=toX(p.time),y=toY(p.price);return x==null||y==null?[]:[{x,y}];});}
function bounds(points:readonly XY[]){if(!points.length)return null;const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y));return{x:minX-TOL,y:minY-TOL,w:maxX-minX+TOL*2,h:maxY-minY+TOL*2};}
function inside(d:Drawing,px:number,py:number,points:readonly XY[]):HitResult[]{const b=bounds(points);return b&&px>=b.x&&px<=b.x+b.w&&py>=b.y&&py<=b.y+b.h?[{drawing:d,target:"body",distance:1}]:[];}
function selectedHandles(g:CanvasRenderingContext2D,d:Drawing,p:readonly XY[],selected:boolean){if(selected)p.forEach(a=>handle(g,a.x,a.y,d.color));}
const targetFor=(index:number):HitResult["target"]=>index===0?"p1":index===1?"p2":index===2?"p3":index===3?"p4":index===4?"p5":"body";
function richAnchors(d:Drawing,toX:HitTestProjector,toY:HitTestProjector):Anchor[]{return d.points.map((point,index)=>({index,x:toX(point.time),y:toY(point.price),target:targetFor(index)}));}
function richAnchorHits(d:Drawing,px:number,py:number,toX:HitTestProjector,toY:HitTestProjector):HitResult[]{return richAnchors(d,toX,toY).flatMap(anchor=>{if(anchor.x==null||anchor.y==null)return[];const distance=Math.hypot(px-anchor.x,py-anchor.y);return distance<=24?[{drawing:d,target:anchor.target,anchorIndex:anchor.index,distance}]:[];});}

const forecast:DrawingToolPlugin={tool:"forecast",minPoints:3,maxPoints:3,render(g,d,proj,selected){const p=projected(d,proj.toX,proj.toY);if(p.length<3)return;const spread=Math.max(8,Math.hypot(p[2].x-p[1].x,p[2].y-p[1].y));const angle=Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x),nx=-Math.sin(angle),ny=Math.cos(angle);g.save();g.fillStyle=d.fillColor||d.color;g.globalAlpha=d.opacity??.14;g.beginPath();g.moveTo(p[0].x,p[0].y);g.lineTo(p[1].x+nx*spread,p[1].y+ny*spread);g.lineTo(p[1].x-nx*spread,p[1].y-ny*spread);g.closePath();g.fill();g.globalAlpha=1;g.strokeStyle=d.color;g.lineWidth=d.lineWidth;g.setLineDash([6,4]);g.beginPath();g.moveTo(p[0].x,p[0].y);g.lineTo(p[1].x,p[1].y);g.stroke();selectedHandles(g,d,p,selected);g.restore();},hitTest(d,px,py,toX,toY){return[...richAnchorHits(d,px,py,toX,toY),...inside(d,px,py,projected(d,toX,toY))];},getAnchors:richAnchors,movePoints:defaultMovePoints,boundingBox(d,toX,toY){return bounds(projected(d,toX,toY));}};
const sector:DrawingToolPlugin={tool:"sector",minPoints:3,maxPoints:3,render(g,d,proj,selected){const p=projected(d,proj.toX,proj.toY);if(p.length<3)return;const radius=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),a1=Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x),a2=Math.atan2(p[2].y-p[0].y,p[2].x-p[0].x);g.save();g.fillStyle=d.fillColor||d.color;g.strokeStyle=d.color;g.lineWidth=d.lineWidth;g.globalAlpha=d.opacity??.15;g.beginPath();g.moveTo(p[0].x,p[0].y);g.arc(p[0].x,p[0].y,radius,a1,a2,a2<a1);g.closePath();g.fill();g.globalAlpha=1;g.stroke();selectedHandles(g,d,p,selected);g.restore();},hitTest(d,px,py,toX,toY){return[...richAnchorHits(d,px,py,toX,toY),...inside(d,px,py,projected(d,toX,toY))];},getAnchors:richAnchors,movePoints:defaultMovePoints,boundingBox(d,toX,toY){const p=projected(d,toX,toY);if(p.length<2)return null;const r=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y);return{x:p[0].x-r-TOL,y:p[0].y-r-TOL,w:r*2+TOL*2,h:r*2+TOL*2};}};

function rectTool(tool:"table"|"image"):DrawingToolPlugin{return{tool,minPoints:2,render(g,d,proj,selected){const p=projected(d,proj.toX,proj.toY);if(p.length<2)return;const x=Math.min(p[0].x,p[1].x),y=Math.min(p[0].y,p[1].y),w=Math.abs(p[1].x-p[0].x),h=Math.abs(p[1].y-p[0].y);g.save();g.fillStyle=d.fillColor||"#131722";g.globalAlpha=d.opacity??.92;g.fillRect(x,y,w,h);g.globalAlpha=1;g.strokeStyle=d.color;g.lineWidth=d.lineWidth;g.strokeRect(x,y,w,h);g.font=canvasFont(d.fontSize??12);g.fillStyle=d.textColor||d.color;if(tool==="table"){const cells=d.content?.kind==="table"&&d.content.cells?.length?d.content.cells:[["Header","Value"],["Row","—"]],rows=cells.length,cols=Math.max(1,...cells.map(r=>r.length));for(let row=1;row<rows;row++){const yy=y+h*row/rows;g.beginPath();g.moveTo(x,yy);g.lineTo(x+w,yy);g.stroke();}for(let col=1;col<cols;col++){const xx=x+w*col/cols;g.beginPath();g.moveTo(xx,y);g.lineTo(xx,y+h);g.stroke();}g.textAlign="center";g.textBaseline="middle";cells.forEach((row,ri)=>row.forEach((cell,ci)=>g.fillText(cell,x+w*(ci+.5)/cols,y+h*(ri+.5)/rows,Math.max(1,w/cols-8))));}else{const alt=d.content?.kind==="image"?(d.content.alt||"Image"):"Image";g.textAlign="center";g.textBaseline="middle";g.fillText(`▧ ${alt}`,x+w/2,y+h/2,Math.max(1,w-12));}selectedHandles(g,d,p,selected);g.restore();},hitTest(d,px,py,toX,toY){return[...richAnchorHits(d,px,py,toX,toY),...inside(d,px,py,projected(d,toX,toY))];},movePoints:defaultMovePoints,boundingBox(d,toX,toY){return bounds(projected(d,toX,toY));}};}

const social:DrawingToolPlugin={tool:"socialEmbed",minPoints:1,render(g,d,proj,selected){const p=projected(d,proj.toX,proj.toY)[0];if(!p)return;const text=(d.text||d.content?.alt||"Paste an X post or TradingView idea URL").slice(0,160),w=Math.min(340,Math.max(180,text.length*6+28)),h=62;g.save();g.fillStyle=d.fillColor||"#131722";g.globalAlpha=d.opacity??.95;g.fillRect(p.x+8,p.y-h/2,w,h);g.globalAlpha=1;g.strokeStyle=d.color;g.strokeRect(p.x+8,p.y-h/2,w,h);g.font=canvasFont(d.fontSize??12);g.fillStyle=d.textColor||"#fff";g.textAlign="left";g.textBaseline="middle";g.fillText("X / TradingView",p.x+20,p.y-14,w-24);g.fillText(text,p.x+20,p.y+12,w-24);selectedHandles(g,d,[p],selected);g.restore();},hitTest(d,px,py,toX,toY){const p=projected(d,toX,toY)[0],body=p&&px>=p.x-TOL&&px<=p.x+360&&py>=p.y-42&&py<=p.y+42?[{drawing:d,target:"body" as const,distance:1}]:[];return[...richAnchorHits(d,px,py,toX,toY),...body];},movePoints:defaultMovePoints,boundingBox(d,toX,toY){const p=projected(d,toX,toY)[0];return p?{x:p.x-TOL,y:p.y-42,w:368,h:84}:null;}};

registerTool(forecast);registerTool(sector);registerTool(rectTool("table"));registerTool(rectTool("image"));registerTool(social);
